name: Deploy Model

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Upload to Deployment Branch
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git checkout -B deployment
          git add .
          git commit -m "Deploying model"
          git push origin deployment --force
